### ISSUE TITLE
license

### ISSUE THREAD

**Issue by heyngra** [frto027/IsaacDisassemblyRate#2]
hey!
I'm writing this issue, because you didn't specify a license. Could I use some parts of this project to my own project I'm currently doing? and also I recommend you add a license to it, so other people know what they can do with project.

**Comment by frto027** [comment]
These codes can be used non-commercially, just mention this repository in any way you want.
`CC BY-NC` will be added.

**Comment by heyngra** [comment]
Okay, thank you a lot!
